name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Instalar dependências com Poetry
        run: poetry install --only docs

      - name: Build da documentação
        run: poetry run mkdocs build

      - name: Publicar na branch gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r site/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy docs from GitHub Actions" || echo "Nada para commit"
          git push origin gh-pages --force
